export const countryCode = [
    { code: 'AG', dial_code: '+1268', name: 'Antigua and Barbuda', img: 'https://flagcdn.com/w40/ag.png' },
    { code: 'AF', dial_code: '+93', name: 'Afghanistan', img: 'https://flagcdn.com/w40/af.png' },
    { code: 'AL', dial_code: '+355', name: 'Albania', img: 'https://flagcdn.com/w40/al.png' },
    { code: 'DZ', dial_code: '+213', name: 'Algeria', img: 'https://flagcdn.com/w40/dz.png' },
    { code: 'AS', dial_code: '+1684', name: 'American Samoa', img: 'https://flagcdn.com/w40/as.png' },
    { code: 'AD', dial_code: '+376', name: 'Andorra', img: 'https://flagcdn.com/w40/ad.png' },
    { code: 'AO', dial_code: '+244', name: 'Angola', img: 'https://flagcdn.com/w40/ao.png' },
    { code: 'AR', dial_code: '+54', name: 'Argentina', img: 'https://flagcdn.com/w40/ar.png' },
    { code: 'AM', dial_code: '+374', name: 'Armenia', img: 'https://flagcdn.com/w40/am.png' },
    { code: 'AU', dial_code: '+61', name: 'Australia', img: 'https://flagcdn.com/w40/au.png' },
    { code: 'AT', dial_code: '+43', name: 'Austria', img: 'https://flagcdn.com/w40/at.png' },
    { code: 'AZ', dial_code: '+994', name: 'Azerbaijan', img: 'https://flagcdn.com/w40/az.png' },
    { code: 'BH', dial_code: '+973', name: 'Bahrain', img: 'https://flagcdn.com/w40/bh.png' },
    { code: 'BD', dial_code: '+880', name: 'Bangladesh', img: 'https://flagcdn.com/w40/bd.png' },
    { code: 'BB', dial_code: '+1246', name: 'Barbados', img: 'https://flagcdn.com/w40/bb.png' },
    { code: 'BY', dial_code: '+375', name: 'Belarus', img: 'https://flagcdn.com/w40/by.png' },
    { code: 'BE', dial_code: '+32', name: 'Belgium', img: 'https://flagcdn.com/w40/be.png' },
    { code: 'BZ', dial_code: '+501', name: 'Belize', img: 'https://flagcdn.com/w40/bz.png' },
    { code: 'BJ', dial_code: '+229', name: 'Benin', img: 'https://flagcdn.com/w40/bj.png' },
    { code: 'BT', dial_code: '+975', name: 'Bhutan', img: 'https://flagcdn.com/w40/bt.png' },
    { code: 'BO', dial_code: '+591', name: 'Bolivia', img: 'https://flagcdn.com/w40/bo.png' },
    { code: 'BA', dial_code: '+387', name: 'Bosnia and Herzegovina', img: 'https://flagcdn.com/w40/ba.png' },
    { code: 'BW', dial_code: '+267', name: 'Botswana', img: 'https://flagcdn.com/w40/bw.png' },
    { code: 'BR', dial_code: '+55', name: 'Brazil', img: 'https://flagcdn.com/w40/br.png' },
    { code: 'BN', dial_code: '+673', name: 'Brunei', img: 'https://flagcdn.com/w40/bn.png' },
    { code: 'BG', dial_code: '+359', name: 'Bulgaria', img: 'https://flagcdn.com/w40/bg.png' },
    { code: 'BF', dial_code: '+226', name: 'Burkina Faso', img: 'https://flagcdn.com/w40/bf.png' },
    { code: 'BI', dial_code: '+257', name: 'Burundi', img: 'https://flagcdn.com/w40/bi.png' },
    { code: 'KH', dial_code: '+855', name: 'Cambodia', img: 'https://flagcdn.com/w40/kh.png' },
    { code: 'CM', dial_code: '+237', name: 'Cameroon', img: 'https://flagcdn.com/w40/cm.png' },
    { code: 'CA', dial_code: '+1', name: 'Canada', img: 'https://flagcdn.com/w40/ca.png' },
    { code: 'CV', dial_code: '+238', name: 'Cape Verde', img: 'https://flagcdn.com/w40/cv.png' },
    { code: 'CF', dial_code: '+236', name: 'Central African Republic', img: 'https://flagcdn.com/w40/cf.png' },
    { code: 'TD', dial_code: '+235', name: 'Chad', img: 'https://flagcdn.com/w40/td.png' },
    { code: 'CL', dial_code: '+56', name: 'Chile', img: 'https://flagcdn.com/w40/cl.png' },
    { code: 'CN', dial_code: '+86', name: 'China', img: 'https://flagcdn.com/w40/cn.png' },
    { code: 'CO', dial_code: '+57', name: 'Colombia', img: 'https://flagcdn.com/w40/co.png' },
    { code: 'KM', dial_code: '+269', name: 'Comoros', img: 'https://flagcdn.com/w40/km.png' },
    { code: 'CG', dial_code: '+242', name: 'Congo', img: 'https://flagcdn.com/w40/cg.png' },
    { code: 'CR', dial_code: '+506', name: 'Costa Rica', img: 'https://flagcdn.com/w40/cr.png' },
    { code: 'HR', dial_code: '+385', name: 'Croatia', img: 'https://flagcdn.com/w40/hr.png' },
    { code: 'CU', dial_code: '+53', name: 'Cuba', img: 'https://flagcdn.com/w40/cu.png' },
    { code: 'CY', dial_code: '+357', name: 'Cyprus', img: 'https://flagcdn.com/w40/cy.png' },
    { code: 'CZ', dial_code: '+420', name: 'Czech Republic', img: 'https://flagcdn.com/w40/cz.png' },
    { code: 'DK', dial_code: '+45', name: 'Denmark', img: 'https://flagcdn.com/w40/dk.png' },
    { code: 'DJ', dial_code: '+253', name: 'Djibouti', img: 'https://flagcdn.com/w40/dj.png' },
    { code: 'DM', dial_code: '+1767', name: 'Dominica', img: 'https://flagcdn.com/w40/dm.png' },
    { code: 'DO', dial_code: '+1809', name: 'Dominican Republic', img: 'https://flagcdn.com/w40/do.png' },
    { code: 'EC', dial_code: '+593', name: 'Ecuador', img: 'https://flagcdn.com/w40/ec.png' },
    { code: 'EG', dial_code: '+20', name: 'Egypt', img: 'https://flagcdn.com/w40/eg.png' },
    { code: 'SV', dial_code: '+503', name: 'El Salvador', img: 'https://flagcdn.com/w40/sv.png' },
    { code: 'GQ', dial_code: '+240', name: 'Equatorial Guinea', img: 'https://flagcdn.com/w40/gq.png' },
    { code: 'ER', dial_code: '+291', name: 'Eritrea', img: 'https://flagcdn.com/w40/er.png' },
    { code: 'EE', dial_code: '+372', name: 'Estonia', img: 'https://flagcdn.com/w40/ee.png' },
    { code: 'ET', dial_code: '+251', name: 'Ethiopia', img: 'https://flagcdn.com/w40/et.png' },
    { code: 'FJ', dial_code: '+679', name: 'Fiji', img: 'https://flagcdn.com/w40/fj.png' },
    { code: 'FI', dial_code: '+358', name: 'Finland', img: 'https://flagcdn.com/w40/fi.png' },
    { code: 'FR', dial_code: '+33', name: 'France', img: 'https://flagcdn.com/w40/fr.png' },
    { code: 'GA', dial_code: '+241', name: 'Gabon', img: 'https://flagcdn.com/w40/ga.png' },
    { code: 'GM', dial_code: '+220', name: 'Gambia', img: 'https://flagcdn.com/w40/gm.png' },
    { code: 'GE', dial_code: '+995', name: 'Georgia', img: 'https://flagcdn.com/w40/ge.png' },
    { code: 'DE', dial_code: '+49', name: 'Germany', img: 'https://flagcdn.com/w40/de.png' },
    { code: 'GH', dial_code: '+233', name: 'Ghana', img: 'https://flagcdn.com/w40/gh.png' },
    { code: 'GR', dial_code: '+30', name: 'Greece', img: 'https://flagcdn.com/w40/gr.png' },
    { code: 'GD', dial_code: '+1473', name: 'Grenada', img: 'https://flagcdn.com/w40/gd.png' },
    { code: 'GT', dial_code: '+502', name: 'Guatemala', img: 'https://flagcdn.com/w40/gt.png' },
    { code: 'GN', dial_code: '+224', name: 'Guinea', img: 'https://flagcdn.com/w40/gn.png' },
    { code: 'GW', dial_code: '+245', name: 'Guinea Bissau', img: 'https://flagcdn.com/w40/gw.png' },
    { code: 'GY', dial_code: '+592', name: 'Guyana', img: 'https://flagcdn.com/w40/gy.png' },
    { code: 'HT', dial_code: '+509', name: 'Haiti', img: 'https://flagcdn.com/w40/ht.png' },
    { code: 'HN', dial_code: '+504', name: 'Honduras', img: 'https://flagcdn.com/w40/hn.png' },
    { code: 'HK', dial_code: '+852', name: 'Hong Kong', img: 'https://flagcdn.com/w40/hk.png' },
    { code: 'HU', dial_code: '+36', name: 'Hungary', img: 'https://flagcdn.com/w40/hu.png' },
    { code: 'IS', dial_code: '+354', name: 'Iceland', img: 'https://flagcdn.com/w40/is.png' },
    { code: 'IN', dial_code: '+91', name: 'India', img: 'https://flagcdn.com/w40/in.png' },
    { code: 'ID', dial_code: '+62', name: 'Indonesia', img: 'https://flagcdn.com/w40/id.png' },
    { code: 'IQ', dial_code: '+964', name: 'Iraq', img: 'https://flagcdn.com/w40/iq.png' },
    { code: 'IE', dial_code: '+353', name: 'Ireland', img: 'https://flagcdn.com/w40/ie.png' },
    { code: 'IT', dial_code: '+39', name: 'Italy', img: 'https://flagcdn.com/w40/it.png' },
    { code: 'JM', dial_code: '+1876', name: 'Jamaica', img: 'https://flagcdn.com/w40/jm.png' },
    { code: 'JP', dial_code: '+81', name: 'Japan', img: 'https://flagcdn.com/w40/jp.png' },
    { code: 'JO', dial_code: '+962', name: 'Jordan', img: 'https://flagcdn.com/w40/jo.png' },
    { code: 'KZ', dial_code: '+7', name: 'Kazakhstan', img: 'https://flagcdn.com/w40/kz.png' },
    { code: 'KE', dial_code: '+254', name: 'Kenya', img: 'https://flagcdn.com/w40/ke.png' },
    { code: 'KI', dial_code: '+686', name: 'Kiribati', img: 'https://flagcdn.com/w40/ki.png' },
    { code: 'KP', dial_code: '+850', name: 'North Korea', img: 'https://flagcdn.com/w40/kp.png' },
    { code: 'KR', dial_code: '+82', name: 'South Korea', img: 'https://flagcdn.com/w40/kr.png' },
    { code: 'KW', dial_code: '+965', name: 'Kuwait', img: 'https://flagcdn.com/w40/kw.png' },
    { code: 'KG', dial_code: '+996', name: 'Kyrgyzstan', img: 'https://flagcdn.com/w40/kg.png' },
    { code: 'LA', dial_code: '+856', name: 'Laos', img: 'https://flagcdn.com/w40/la.png' },
    { code: 'LV', dial_code: '+371', name: 'Latvia', img: 'https://flagcdn.com/w40/lv.png' },
    { code: 'LB', dial_code: '+961', name: 'Lebanon', img: 'https://flagcdn.com/w40/lb.png' },
    { code: 'LS', dial_code: '+266', name: 'Lesotho', img: 'https://flagcdn.com/w40/ls.png' },
    { code: 'LR', dial_code: '+231', name: 'Liberia', img: 'https://flagcdn.com/w40/lr.png' },
    { code: 'LY', dial_code: '+218', name: 'Libya', img: 'https://flagcdn.com/w40/ly.png' },
    { code: 'LI', dial_code: '+423', name: 'Liechtenstein', img: 'https://flagcdn.com/w40/li.png' },
    { code: 'LT', dial_code: '+370', name: 'Lithuania', img: 'https://flagcdn.com/w40/lt.png' },
    { code: 'LU', dial_code: '+352', name: 'Luxembourg', img: 'https://flagcdn.com/w40/lu.png' },
    { code: 'MO', dial_code: '+853', name: 'Macau', img: 'https://flagcdn.com/w40/mo.png' },
    { code: 'MG', dial_code: '+261', name: 'Madagascar', img: 'https://flagcdn.com/w40/mg.png' },
    { code: 'MW', dial_code: '+265', name: 'Malawi', img: 'https://flagcdn.com/w40/mw.png' },
    { code: 'MY', dial_code: '+60', name: 'Malaysia', img: 'https://flagcdn.com/w40/my.png' },
    { code: 'MV', dial_code: '+960', name: 'Maldives', img: 'https://flagcdn.com/w40/mv.png' },
    { code: 'ML', dial_code: '+223', name: 'Mali', img: 'https://flagcdn.com/w40/ml.png' },
    { code: 'MT', dial_code: '+356', name: 'Malta', img: 'https://flagcdn.com/w40/mt.png' },
    { code: 'MH', dial_code: '+692', name: 'Marshall Islands', img: 'https://flagcdn.com/w40/mh.png' },
    { code: 'MR', dial_code: '+222', name: 'Mauritania', img: 'https://flagcdn.com/w40/mr.png' },
    { code: 'MU', dial_code: '+230', name: 'Mauritius', img: 'https://flagcdn.com/w40/mu.png' },
    { code: 'MX', dial_code: '+52', name: 'Mexico', img: 'https://flagcdn.com/w40/mx.png' },
    { code: 'FM', dial_code: '+691', name: 'Micronesia', img: 'https://flagcdn.com/w40/fm.png' },
    { code: 'MD', dial_code: '+373', name: 'Moldova', img: 'https://flagcdn.com/w40/md.png' },
    { code: 'MC', dial_code: '+377', name: 'Monaco', img: 'https://flagcdn.com/w40/mc.png' },
    { code: 'MN', dial_code: '+976', name: 'Mongolia', img: 'https://flagcdn.com/w40/mn.png' },
    { code: 'ME', dial_code: '+382', name: 'Montenegro', img: 'https://flagcdn.com/w40/me.png' },
    { code: 'MA', dial_code: '+212', name: 'Morocco', img: 'https://flagcdn.com/w40/ma.png' },
    { code: 'MZ', dial_code: '+258', name: 'Mozambique', img: 'https://flagcdn.com/w40/mz.png' },
    { code: 'MM', dial_code: '+95', name: 'Myanmar', img: 'https://flagcdn.com/w40/mm.png' },
    { code: 'NA', dial_code: '+264', name: 'Namibia', img: 'https://flagcdn.com/w40/na.png' },
    { code: 'NR', dial_code: '+674', name: 'Nauru', img: 'https://flagcdn.com/w40/nr.png' },
    { code: 'NP', dial_code: '+977', name: 'Nepal', img: 'https://flagcdn.com/w40/np.png' },
    { code: 'NL', dial_code: '+31', name: 'Netherlands', img: 'https://flagcdn.com/w40/nl.png' },
    { code: 'NZ', dial_code: '+64', name: 'New Zealand', img: 'https://flagcdn.com/w40/nz.png' },
    { code: 'NI', dial_code: '+505', name: 'Nicaragua', img: 'https://flagcdn.com/w40/ni.png' },
    { code: 'NE', dial_code: '+227', name: 'Niger', img: 'https://flagcdn.com/w40/ne.png' },
    { code: 'NG', dial_code: '+234', name: 'Nigeria', img: 'https://flagcdn.com/w40/ng.png' },
    { code: 'NO', dial_code: '+47', name: 'Norway', img: 'https://flagcdn.com/w40/no.png' },
    { code: 'OM', dial_code: '+968', name: 'Oman', img: 'https://flagcdn.com/w40/om.png' },
    { code: 'PK', dial_code: '+92', name: 'Pakistan', img: 'https://flagcdn.com/w40/pk.png' },
    { code: 'PW', dial_code: '+680', name: 'Palau', img: 'https://flagcdn.com/w40/pw.png' },
    { code: 'PA', dial_code: '+507', name: 'Panama', img: 'https://flagcdn.com/w40/pa.png' },
    { code: 'PG', dial_code: '+675', name: 'Papua New Guinea', img: 'https://flagcdn.com/w40/pg.png' },
    { code: 'PY', dial_code: '+595', name: 'Paraguay', img: 'https://flagcdn.com/w40/py.png' },
    { code: 'PE', dial_code: '+51', name: 'Peru', img: 'https://flagcdn.com/w40/pe.png' },
    { code: 'PH', dial_code: '+63', name: 'Philippines', img: 'https://flagcdn.com/w40/ph.png' },
    { code: 'PL', dial_code: '+48', name: 'Poland', img: 'https://flagcdn.com/w40/pl.png' },
    { code: 'PT', dial_code: '+351', name: 'Portugal', img: 'https://flagcdn.com/w40/pt.png' },
    { code: 'QA', dial_code: '+974', name: 'Qatar', img: 'https://flagcdn.com/w40/qa.png' },
    { code: 'RO', dial_code: '+40', name: 'Romania', img: 'https://flagcdn.com/w40/ro.png' },
    { code: 'RU', dial_code: '+7', name: 'Russia', img: 'https://flagcdn.com/w40/ru.png' },
    { code: 'RW', dial_code: '+250', name: 'Rwanda', img: 'https://flagcdn.com/w40/rw.png' },
    { code: 'KN', dial_code: '+1869', name: 'Saint Kitts and Nevis', img: 'https://flagcdn.com/w40/kn.png' },
    { code: 'LC', dial_code: '+1758', name: 'Saint Lucia', img: 'https://flagcdn.com/w40/lc.png' },
    { code: 'VC', dial_code: '+1784', name: 'Saint Vincent and the Grenadines', img: 'https://flagcdn.com/w40/vc.png' },
    { code: 'WS', dial_code: '+685', name: 'Samoa', img: 'https://flagcdn.com/w40/ws.png' },
    { code: 'SM', dial_code: '+378', name: 'San Marino', img: 'https://flagcdn.com/w40/sm.png' },
    { code: 'ST', dial_code: '+239', name: 'Sao Tome and Principe', img: 'https://flagcdn.com/w40/st.png' },
    { code: 'SA', dial_code: '+966', name: 'Saudi Arabia', img: 'https://flagcdn.com/w40/sa.png' },
    { code: 'SN', dial_code: '+221', name: 'Senegal', img: 'https://flagcdn.com/w40/sn.png' },
    { code: 'RS', dial_code: '+381', name: 'Serbia', img: 'https://flagcdn.com/w40/rs.png' },
    { code: 'SC', dial_code: '+248', name: 'Seychelles', img: 'https://flagcdn.com/w40/sc.png' },
    { code: 'SL', dial_code: '+232', name: 'Sierra Leone', img: 'https://flagcdn.com/w40/sl.png' },
    { code: 'SG', dial_code: '+65', name: 'Singapore', img: 'https://flagcdn.com/w40/sg.png' },
    { code: 'SK', dial_code: '+421', name: 'Slovakia', img: 'https://flagcdn.com/w40/sk.png' },
    { code: 'SI', dial_code: '+386', name: 'Slovenia', img: 'https://flagcdn.com/w40/si.png' },
    { code: 'SB', dial_code: '+677', name: 'Solomon Islands', img: 'https://flagcdn.com/w40/sb.png' },
    { code: 'SO', dial_code: '+252', name: 'Somalia', img: 'https://flagcdn.com/w40/so.png' },
    { code: 'ZA', dial_code: '+27', name: 'South Africa', img: 'https://flagcdn.com/w40/za.png' },
    { code: 'SS', dial_code: '+211', name: 'South Sudan', img: 'https://flagcdn.com/w40/ss.png' },
    { code: 'ES', dial_code: '+34', name: 'Spain', img: 'https://flagcdn.com/w40/es.png' },
    { code: 'LK', dial_code: '+94', name: 'Sri Lanka', img: 'https://flagcdn.com/w40/lk.png' },
    { code: 'SD', dial_code: '+249', name: 'Sudan', img: 'https://flagcdn.com/w40/sd.png' },
    { code: 'SR', dial_code: '+597', name: 'Suriname', img: 'https://flagcdn.com/w40/sr.png' },
    { code: 'SZ', dial_code: '+268', name: 'Eswatini', img: 'https://flagcdn.com/w40/sz.png' },
    { code: 'SE', dial_code: '+46', name: 'Sweden', img: 'https://flagcdn.com/w40/se.png' },
    { code: 'CH', dial_code: '+41', name: 'Switzerland', img: 'https://flagcdn.com/w40/ch.png' },
    { code: 'SY', dial_code: '+963', name: 'Syria', img: 'https://flagcdn.com/w40/sy.png' },
    { code: 'TW', dial_code: '+886', name: 'Taiwan', img: 'https://flagcdn.com/w40/tw.png' },
    { code: 'TJ', dial_code: '+992', name: 'Tajikistan', img: 'https://flagcdn.com/w40/tj.png' },
    { code: 'TZ', dial_code: '+255', name: 'Tanzania', img: 'https://flagcdn.com/w40/tz.png' },
    { code: 'TH', dial_code: '+66', name: 'Thailand', img: 'https://flagcdn.com/w40/th.png' },
    { code: 'TL', dial_code: '+670', name: 'Timor Leste', img: 'https://flagcdn.com/w40/tl.png' },
    { code: 'TG', dial_code: '+228', name: 'Togo', img: 'https://flagcdn.com/w40/tg.png' },
    { code: 'TO', dial_code: '+676', name: 'Tonga', img: 'https://flagcdn.com/w40/to.png' },
    { code: 'TT', dial_code: '+1868', name: 'Trinidad and Tobago', img: 'https://flagcdn.com/w40/tt.png' },
    { code: 'TN', dial_code: '+216', name: 'Tunisia', img: 'https://flagcdn.com/w40/tn.png' },
    { code: 'TR', dial_code: '+90', name: 'Turkey', img: 'https://flagcdn.com/w40/tr.png' },
    { code: 'TM', dial_code: '+993', name: 'Turkmenistan', img: 'https://flagcdn.com/w40/tm.png' },
    { code: 'TV', dial_code: '+688', name: 'Tuvalu', img: 'https://flagcdn.com/w40/tv.png' },
    { code: 'UG', dial_code: '+256', name: 'Uganda', img: 'https://flagcdn.com/w40/ug.png' },
    { code: 'UA', dial_code: '+380', name: 'Ukraine', img: 'https://flagcdn.com/w40/ua.png' },
    { code: 'AE', dial_code: '+971', name: 'United Arab Emirates', img: 'https://flagcdn.com/w40/ae.png' },
    { code: 'GB', dial_code: '+44', name: 'United Kingdom', img: 'https://flagcdn.com/w40/gb.png' },
    { code: 'US', dial_code: '+1', name: 'United States', img: 'https://flagcdn.com/w40/us.png' },
    { code: 'UY', dial_code: '+598', name: 'Uruguay', img: 'https://flagcdn.com/w40/uy.png' },
    { code: 'UZ', dial_code: '+998', name: 'Uzbekistan', img: 'https://flagcdn.com/w40/uz.png' },
    { code: 'VU', dial_code: '+678', name: 'Vanuatu', img: 'https://flagcdn.com/w40/vu.png' },
    { code: 'VA', dial_code: '+379', name: 'Vatican City', img: 'https://flagcdn.com/w40/va.png' },
    { code: 'VE', dial_code: '+58', name: 'Venezuela', img: 'https://flagcdn.com/w40/ve.png' },
    { code: 'VN', dial_code: '+84', name: 'Vietnam', img: 'https://flagcdn.com/w40/vn.png' },
    { code: 'YE', dial_code: '+967', name: 'Yemen', img: 'https://flagcdn.com/w40/ye.png' },
    { code: 'ZM', dial_code: '+260', name: 'Zambia', img: 'https://flagcdn.com/w40/zm.png' },
    { code: 'ZW', dial_code: '+263', name: 'Zimbabwe', img: 'https://flagcdn.com/w40/zw.png' }
];

